[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite/0.9.0"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.10.0-alpha.1"
edition = "2018"

[features]
default = ["connect", "tls"]
connect = ["tokio-net", "stream"]
tls = ["tokio-tls", "native-tls", "stream", "tungstenite/tls"]
stream = ["bytes"]

[dependencies]
log = "0.4"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
pin-project = "0.4"
tokio-io = "0.2.0-alpha.6"

[dependencies.tungstenite]
#version = "0.9.1"
git = "https://github.com/snapview/tungstenite-rs.git"
branch = "master"
default-features = false

[dependencies.bytes]
optional = true
version = "0.4.8"

[dependencies.native-tls]
optional = true
version = "0.2.0"

[dependencies.tokio-net]
version = "0.2.0-alpha.6"
#git = "https://github.com/tokio-rs/tokio.git"
optional = true
features = ["tcp"]

[dependencies.tokio-tls]
version = "0.3.0-alpha.6"
optional = true
#git = "https://github.com/tokio-rs/tokio.git"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
url = "2.0.0"
env_logger = "0.7"
